import Navbar from "./components/navbar";
import "./globals.css";
import { Roboto } from "next/font/google";
import { register } from "swiper/element/bundle";

const roboto = Roboto({
  subsets: ["latin"],
  weight: "700",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  register();

  return (
    <html lang='en'>
      <body className={roboto.className}>
        <Navbar />

        {children}
      </body>
    </html>
  );
}
